[build]
  functions = "netlify/functions"

[functions]
  # Мы просто убираем проблемную строку. 
  # По умолчанию Netlify и так использует актуальную версию Node.js.
  external_node_modules = ["@netlify/blobs"]

[blobs]
  auto_install = true
  
