[build]
  functions = "netlify/functions"

[functions]
  # Мы просто убираем node_compatibility, так как современные рантаймы 
  # Netlify и так поддерживают Blobs по умолчанию.
  external_node_modules = ["@netlify/blobs"]

[blobs]
  auto_install = true
  
