[build]
  functions = "netlify/functions"

[functions]
  node_compatibility = "v18" # Blobs требуют свежую Node.js

[blobs]
  # Эта настройка автоматически связывает функции с базой
  auto_install = true
  
